# Add account credentials and API keys here.
# See http://railsapps.github.io/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
# Add application configuration variables here, as shown below.
#
BRAINTREE_SANDBOX_ENVIRONMENT: sandbox
BRAINTREE_SANDBOX_MERCHANT_ID: sandbox_merchant_id
BRAINTREE_SANDBOX_MASTER_MERCHANT_ID: sandbox_master_merchant_id
BRAINTREE_SANDBOX_PUBLIC_KEY: sandbox_public_key
BRAINTREE_SANDBOX_PRIVATE_KEY: sandbox_private_key
MANDRILL_USERNAME: username
MANDRILL_API_KEY: api
MAILCHIMP_API_KEY: api
ADMIN_NAME: admin
ADMIN_EMAIL: admin@example.com
ADMIN_PASSWORD: admin123
FACEBOOK_APPID: appid
FACEBOOK_APPSECRET: appsecret
GOOGLE_APPID: appid
GOOGLE_APPSECRET: appsecret
TWITTER_APPID: appid
TWITTER_APPSECRET: appsecret
AWS_BUCKET: bucket
AWS_ACCESS_KEY_ID: keyid
AWS_SECRET_ACCESS_KEY: accesskey
ROLES: [admin, user, VIP]